format: 
  pdf: 
    documentclass: report
    fontsize: 11pt
book:
  chapters:
    - index.qmd
    - hardware-solutions.qmd
    - software-solutions.qmd
    - real-world-use.qmd
    - appendices.qmd
    - references.qmd
    - abbreviations.qmd
