project:
  type: book
  
book:
  title: "Build-It-Yourself: Low-Cost Systems for Field Ecophysiology"
  subtitle: "An Open Handbook for DIY Environmental Measurement Systems"
  date: last-modified
  search: true
  repo-url: https://github.com/zalf-lli/LCSfFE-handbook
  repo-actions: [edit]
  downloads: [pdf]
  favicon: assets/mhl-logo.png

  sidebar:
    pinned: true
    logo: assets/mhl-logo.png
    alignment: center
    style: "docked"
    title: " "
    tools:
      - icon: envelope
        href: mailto:mathiashoffmann@zalf.de
    contents: 
      - text: "Home"
        href: index.qmd
      # - text: "Introduction"
      #   href: intro.qmd
      - text: "Hardware Solutions"
        href: hardware-solutions.qmd
      - text: "Software Solutions"
        href: software-solutions.qmd
      - text: "Real-World Use Cases"
        href: real-world-use.qmd
      - text: "References"
        href: references.qmd
      - text: "Abbreviations"
        href: abbreviations.qmd

  page-footer: "License: Creative Commons Attribution 4.0 (CC-BY 4.0)" 
  chapters: 
    - index.qmd    
    - abbreviations.qmd
    - hardware-solutions.qmd
    - software-solutions.qmd
    - real-world-use.qmd
    - references.qmd


bibliography: references.bib
number-depth: 4
glossary:
  path: glossary.yml
  popup: hover
  show: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    lightbox: true
  # embed-resources: true
  # pdf:
  #   documentclass: scrreprt

comments:
  hypothesis: true



